import Head from 'next/head';
import React, {useState} from "react";

export default function Home() {

  const [myVideo, setCreateVideo] = useState(null)
  const [isLoading, setLoading] = useState(false)

  function createVideo(){
    setLoading(true)

    //Something like this would be ideal, but not sure if possible...

    /*
    const options = {
      method: 'POST',
      headers: {
      'Content-Type': 'application/json'
      },
      body: JSON.stringify({video_title: 'Hello, world', video_content: "Demo"})
    };
    
    fetch('api/render-video',options)
      .then((res) => res.json())
      .then((data) => {
        setCreateVideo(data)
        setLoading(false)
      }).catch((err)=>{setLoading(false);console.log(err)})*/
      
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello world</h1>
      <h2>{isLoading ? "Loading..." : "Not loading"}</h2>
      <button type="submit" disabled onClick={createVideo}>This button is not working yet,<br /> but should create a video on click</button>
    </div>
  )
}
